### ISSUE TITLE
Possible duplicate rows in MCA data

### ISSUE THREAD

**Issue by Radcliffe** [SocialDataSci/bridgethegap#1]
There are rows in the data set that seem to contain duplicate or conflicting values.

Assumption: No two rows can have the same values for all of the variables dataYear, testname, subject, grade, districtNumber, districtType, schoolNumber, and ReportDescription; unless schoolName == "All Schools".

Observation: There are 50 rows that are exact duplicates of other rows, and 60 rows containing data that contradict other rows.

Resolution: Beats me?

[MCA-duplicate-rows.txt](https://github.com/SocialDataSci/bridgethegap/files/83919/MCA-duplicate-rows.txt)

**Comment by dreyco676** [comment]
I emailed Jonathan to see what he thinks.

**Comment by jonathanmay528** [comment]
it has to be some sort of aggregation. I'll look at the raw data when I'm in front of my computer tomorrow.

**Comment by Radcliffe** [comment]
The raw data for MCA-II Nonpublic has 50 duplicate rows, which can be listed by typing the following command in a Unix terminal window.

$ sort 011534.Tab | uniq -d

**Comment by Radcliffe** [comment]
I think that I have resolved the issue. There are 50 duplicate rows, and they can be safely deleted. As for the other 60 rows, they have different values of schoolClassification, even though the school name and number are the same.

**Comment by jonathanmay528** [comment]
Great, thanks, David. Feel free to reach out if you have more questions!

Jonathan May
jonathanmay528@gmail.com

On Sun, Jan 10, 2016 at 9:00 PM -0800, "David Radcliffe" notifications@github.com wrote:

I think that I have resolved the issue. There are 50 duplicate rows, and they can be safely deleted. As for the other 60 rows, they have different values of schoolClassification, even though the school name and number are the same.
